package controllers;

public enum ComandApp {
	
	ADD_REGION,ELIMINAR_REGION,MODIFICAR_REGION,MOSTRAR_REGION,
	ADD_WORK,ELIMINAR_WORK,MODIFICAR_WORK,MOSTRAR_WORK,
	ADD_PAIS,ELIMINAR_PAIS,MODIFICAR_PAIS,MOSTRAR_PAIS,
	ADD_UBICACION,ELIMINAR_UBICACION,MODIFICAR_UBICACION,MOSTRAR_UBICACION,
	ADD_HYSTORY_WORK,ELIMINAR_HYSTORY_WORK,MODIFICAR_HYSTORY_WORK,MOSTRAR_HYSTORY_WORK,
	ADD_DEPARTAMENTO,ELIMINAR_DEPARTAMENTO,MODIFICAR_DEPARTAMENTO,MOSTRAR_DEPARTAMENTO,
	ADD_EMPLEADO,ELIMINAR_EMPLEADO,MODIFICAR_EMPLEADO,MOSTRAR_EMPLEADO,
}
